name: Compilar Proyecto Android ZIP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el codigo del repositorio
      uses: actions/checkout@v4

    - name: Configurar Java 17 (Requerido para Android)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Instalar Gradle en el Servidor
      uses: gradle/actions/setup-gradle@v4

    - name: Descomprimir y buscar el proyecto
      run: |
        unzip *.zip
        
        # Buscar en qué subcarpeta quedaron los archivos de configuracion
        CONFIG_PATH=$(find . -name "settings.gradle.kts" | head -n 1)
        
        if [ -z "$CONFIG_PATH" ]; then
          echo "ERROR: No se encontro settings.gradle.kts dentro del ZIP."
          exit 1
        fi
        
        PROJECT_DIR=$(dirname "$CONFIG_PATH")
        echo "PROJECT_ROOT=$PROJECT_DIR" >> $GITHUB_ENV
        echo "Proyecto Android detectado en: $PROJECT_DIR"

    - name: Compilar aplicacion Android (Build)
      run: |
        cd ${{ env.PROJECT_ROOT }}
        gradle build --no-daemon
